// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK4_Y-jbjJ3OfIwo4m0ad8lEOC06POrlc',
    appId: '1:69421126144:web:90777c528cd34989cffee5',
    messagingSenderId: '69421126144',
    projectId: 'first-app-bea75',
    authDomain: 'first-app-bea75.firebaseapp.com',
    storageBucket: 'first-app-bea75.appspot.com',
    measurementId: 'G-N2T670EXRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv4SvrxoPXTI-Ni3rbKW5lnx8GaRZpZf4',
    appId: '1:69421126144:android:1eed6fd58680f45ccffee5',
    messagingSenderId: '69421126144',
    projectId: 'first-app-bea75',
    storageBucket: 'first-app-bea75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeKMERuvCe-tl_DBHV9egvxtXNLyPmjBs',
    appId: '1:69421126144:ios:5c0008b26efd9ad8cffee5',
    messagingSenderId: '69421126144',
    projectId: 'first-app-bea75',
    storageBucket: 'first-app-bea75.appspot.com',
    iosBundleId: 'com.example.studentApp',
  );
}
